### ISSUE TITLE
typo in readme 

### ISSUE THREAD

**Issue by sachincool** [thakursaurabh1998/linux-server-config#1]
Readme 
Typo 
`Summamry of software installed`

**Comment by thakursaurabh1998** [comment]
This was just a practice repository and it can have some errors. You can see the more detailed version of the configuration at https://github.com/thakursaurabh1998/linux-server-setup
If you find any errors there, let me know I will be obliged.

**Comment by thakursaurabh1998** [comment]
Anyway this typo will be fixed.
